# Copyright 2023 GrapheneOS
# Use of this source code is governed by a GPL-2.0-only-style license that can be
# found in the LICENSE file.

chrome_ext_java_resources = [
  "java/res/xml/privacy_preferences_ext.xml",
  "java/res/layout/webrtc_policy_preference.xml",
  "java/res/xml/webrtc_policy_preferences.xml",
]
