# Copyright 2023 GrapheneOS
# Use of this source code is governed by a GPL-2.0-only-style license that can be
# found in the LICENSE file.

chrome_ext_java_sources = [
  "java/src/org/chromium/chrome/browser/settings/SettingsExtUtils.java",
  "java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettingsExt.java",
  "java/src/org/chromium/chrome/browser/TabPreferencesUtils.java",
  "java/src/org/chromium/chrome/browser/LaunchIntentDispatcherHooks.java",
  "java/src/org/chromium/chrome/browser/searchwidget/SearchActivityHooks.java",
  "java/src/org/chromium/chrome/browser/webrtc/settings/WebRtcPolicyPreference.java",
  "java/src/org/chromium/chrome/browser/webrtc/settings/WebRtcPolicySettings.java",
  "java/src/org/chromium/chrome/browser/webrtc/settings/WebRtcPolicyUtils.java",
]
