# Copyright 2023 GrapheneOS
# Use of this source code is governed by a GPL-2.0-only-style license that can be
# found in the LICENSE file.

chrome_ext_java_sources = [
  "java/src/org/chromium/chrome/browser/settings/SettingsExtUtils.java",
  "java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettingsExt.java",
  "java/src/org/chromium/chrome/browser/TabPreferencesUtils.java",
]
