# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/channel.gni")
import("//build/config/android/config.gni")
import("//build/config/android/rules.gni")
import("//vanadium/android_config/config_apk.gni")

assert(is_android)

config_apk_tmpl("vanadium_config_apk") {
  apk_name = "VanadiumConfig"
  application_label = "Vanadium Config"
  deps = [
    "filter_lists:ruleset_assets",
    "proto:config_assets",
  ]
}

config_apk_tmpl("vanadium_config_for_testing_apk") {
  testonly = true
  apk_name = "VanadiumConfigTest"
  application_label = "Vanadium Config Test"
}

# An empty group included in //BUILD.gn to make this and other config apk type build
# files reachable by GN.
group("empty_group") {
}

generate_configinfo_srcjar("configinfo_srcjar_build") {
  use_final_fields = false
}

# Use this to declare dependency on ConfigInfo class
java_library("configinfo_java") {
  supports_android = true
  srcjar_deps = [
    ":configinfo_srcjar_build",
  ]
  # New version of ConfigInfo.java (with the actual correct values) will
  # be created when creating an apk.
  jar_excluded_patterns = [ "*/ConfigInfo.class" ]
}

generate_configinfo_srcjar("configinfo_srcjar_apk") {
  use_final_fields = true
}
